//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsWay.WinTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WitsWay.WinTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add1 {
            get {
                object obj = ResourceManager.GetObject("add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br&gt;&lt;br&gt;Address: &lt;b&gt;{0}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string AddressHtml {
            get {
                return ResourceManager.GetString("AddressHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Analytics {
            get {
                object obj = ResourceManager.GetObject("Analytics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Announcements 的本地化字符串。
        /// </summary>
        internal static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap application_edit {
            get {
                object obj = ResourceManager.GetObject("application_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap application_view_tile {
            get {
                object obj = ResourceManager.GetObject("application_view_tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Error: could not export appointments 的本地化字符串。
        /// </summary>
        internal static string AppointmentError {
            get {
                return ResourceManager.GetString("AppointmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ASP 的本地化字符串。
        /// </summary>
        internal static string ASP {
            get {
                return ResourceManager.GetString("ASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BandedReports {
            get {
                object obj = ResourceManager.GetObject("BandedReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br&gt;Birth Date: &lt;b&gt;{0:d}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string BirthDateHtml {
            get {
                return ResourceManager.GetString("BirthDateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BO_Task {
            get {
                object obj = ResourceManager.GetObject("BO_Task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BO_Task_Large {
            get {
                object obj = ResourceManager.GetObject("BO_Task_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ByState_32x32 {
            get {
                object obj = ResourceManager.GetObject("ByState_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar 的本地化字符串。
        /// </summary>
        internal static string CalendarName {
            get {
                return ResourceManager.GetString("CalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Card_32x32 {
            get {
                object obj = ResourceManager.GetObject("Card_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Close_16x16 {
            get {
                object obj = ResourceManager.GetObject("Close_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Close_32x32 {
            get {
                object obj = ResourceManager.GetObject("Close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Close the current search. 的本地化字符串。
        /// </summary>
        internal static string CloseSearchDescription {
            get {
                return ResourceManager.GetString("CloseSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Code_Central {
            get {
                object obj = ResourceManager.GetObject("Code_Central", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Collated 的本地化字符串。
        /// </summary>
        internal static string Collated {
            get {
                return ResourceManager.GetString("Collated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1,2,3   1,2,3  1,2,3 的本地化字符串。
        /// </summary>
        internal static string CollatedDescription {
            get {
                return ResourceManager.GetString("CollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ColorMixer_32x32 {
            get {
                object obj = ResourceManager.GetObject("ColorMixer_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Completed_16x16 {
            get {
                object obj = ResourceManager.GetObject("Completed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Completed_32x32 {
            get {
                object obj = ResourceManager.GetObject("Completed_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Contact 的本地化字符串。
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Contact_16x16 {
            get {
                object obj = ResourceManager.GetObject("Contact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Contact_32x32 {
            get {
                object obj = ResourceManager.GetObject("Contact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Contact_Us {
            get {
                object obj = ResourceManager.GetObject("Contact_Us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 List contacts in alphabetical order. 的本地化字符串。
        /// </summary>
        internal static string ContactAlphabeticalDescription {
            get {
                return ResourceManager.GetString("ContactAlphabeticalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group contacts by the states. 的本地化字符串。
        /// </summary>
        internal static string ContactByStateDescription {
            get {
                return ResourceManager.GetString("ContactByStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display card presentation. 的本地化字符串。
        /// </summary>
        internal static string ContactCardDescription {
            get {
                return ResourceManager.GetString("ContactCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List contacts in the order of creation. 的本地化字符串。
        /// </summary>
        internal static string ContactListDescription {
            get {
                return ResourceManager.GetString("ContactListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        internal static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dr. 的本地化字符串。
        /// </summary>
        internal static string ContactTitleDr {
            get {
                return ResourceManager.GetString("ContactTitleDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miss 的本地化字符串。
        /// </summary>
        internal static string ContactTitleMiss {
            get {
                return ResourceManager.GetString("ContactTitleMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mr. 的本地化字符串。
        /// </summary>
        internal static string ContactTitleMr {
            get {
                return ResourceManager.GetString("ContactTitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mrs. 的本地化字符串。
        /// </summary>
        internal static string ContactTitleMrs {
            get {
                return ResourceManager.GetString("ContactTitleMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ms. 的本地化字符串。
        /// </summary>
        internal static string ContactTitleMs {
            get {
                return ResourceManager.GetString("ContactTitleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prof. 的本地化字符串。
        /// </summary>
        internal static string ContactTitleProf {
            get {
                return ResourceManager.GetString("ContactTitleProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV files (*.csv)|*.csv 的本地化字符串。
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Custom_Flag {
            get {
                object obj = ResourceManager.GetObject("Custom_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string DateDeleted {
            get {
                return ResourceManager.GetString("DateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        internal static string DateInbox {
            get {
                return ResourceManager.GetString("DateInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        internal static string DateOutbox {
            get {
                return ResourceManager.GetString("DateOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Deferred_32x32 {
            get {
                object obj = ResourceManager.GetObject("Deferred_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("Delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this contact. 的本地化字符串。
        /// </summary>
        internal static string DeleteContactDescription {
            get {
                return ResourceManager.GetString("DeleteContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted Items 的本地化字符串。
        /// </summary>
        internal static string DeletedItems {
            get {
                return ResourceManager.GetString("DeletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this feed. 的本地化字符串。
        /// </summary>
        internal static string DeleteFeedDescription {
            get {
                return ResourceManager.GetString("DeleteFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this item. 的本地化字符串。
        /// </summary>
        internal static string DeleteItemDescription {
            get {
                return ResourceManager.GetString("DeleteItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this task. 的本地化字符串。
        /// </summary>
        internal static string DeleteTaskDescription {
            get {
                return ResourceManager.GetString("DeleteTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DevExpress {
            get {
                object obj = ResourceManager.GetObject("DevExpress", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Doctor {
            get {
                object obj = ResourceManager.GetObject("Doctor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Drafts 的本地化字符串。
        /// </summary>
        internal static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due Date can&apos;t be less than Start Date 的本地化字符串。
        /// </summary>
        internal static string DueDateError {
            get {
                return ResourceManager.GetString("DueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter Due Date 的本地化字符串。
        /// </summary>
        internal static string DueDateWarning {
            get {
                return ResourceManager.GetString("DueDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditContact_16x16 {
            get {
                object obj = ResourceManager.GetObject("EditContact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditContact_32x32 {
            get {
                object obj = ResourceManager.GetObject("EditContact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Edit this contact. 的本地化字符串。
        /// </summary>
        internal static string EditContactDescription {
            get {
                return ResourceManager.GetString("EditContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit this feed&apos;s settings. 的本地化字符串。
        /// </summary>
        internal static string EditFeedDescription {
            get {
                return ResourceManager.GetString("EditFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditTask_16x16 {
            get {
                object obj = ResourceManager.GetObject("EditTask_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditTask_32x32 {
            get {
                object obj = ResourceManager.GetObject("EditTask_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Edit this task. 的本地化字符串。
        /// </summary>
        internal static string EditTaskDescription {
            get {
                return ResourceManager.GetString("EditTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br&gt;Email: &lt;b&gt;{0}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string EmailHtml {
            get {
                return ResourceManager.GetString("EmailHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while exporting 的本地化字符串。
        /// </summary>
        internal static string ExportErrorText {
            get {
                return ResourceManager.GetString("ExportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToCSV_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToCSV_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToHTML_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToHTML_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToImage_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToImage_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToMHT_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToMHT_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToPDF_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToPDF_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToRTF_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToRTF_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToText_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToText_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToXLS_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToXLS_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportToXLSX_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToXLSX_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 BBC News 的本地化字符串。
        /// </summary>
        internal static string FeedBBCNews {
            get {
                return ResourceManager.GetString("FeedBBCNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blogs 的本地化字符串。
        /// </summary>
        internal static string FeedBlogs {
            get {
                return ResourceManager.GetString("FeedBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engadget 的本地化字符串。
        /// </summary>
        internal static string FeedEngadget {
            get {
                return ResourceManager.GetString("FeedEngadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please accept our apologies for the inconvenience. The feed URL is currently unavailable:&lt;br&gt;&lt;b&gt;{0} 的本地化字符串。
        /// </summary>
        internal static string FeedError {
            get {
                return ResourceManager.GetString("FeedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevExpress 的本地化字符串。
        /// </summary>
        internal static string FeedGroupDX {
            get {
                return ResourceManager.GetString("FeedGroupDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misc 的本地化字符串。
        /// </summary>
        internal static string FeedGroupMisc {
            get {
                return ResourceManager.GetString("FeedGroupMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News 的本地化字符串。
        /// </summary>
        internal static string FeedNews {
            get {
                return ResourceManager.GetString("FeedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt; &lt;/b&gt;Content is taken from the public &lt;color={1}&gt;{0}&lt;/color&gt; feed 的本地化字符串。
        /// </summary>
        internal static string FeedNote {
            get {
                return ResourceManager.GetString("FeedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feeds 的本地化字符串。
        /// </summary>
        internal static string FeedsName {
            get {
                return ResourceManager.GetString("FeedsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Overflow 的本地化字符串。
        /// </summary>
        internal static string FeedStackOverflow {
            get {
                return ResourceManager.GetString("FeedStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Videos 的本地化字符串。
        /// </summary>
        internal static string FeedVideos {
            get {
                return ResourceManager.GetString("FeedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webinars 的本地化字符串。
        /// </summary>
        internal static string FeedWebinars {
            get {
                return ResourceManager.GetString("FeedWebinars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task with custom due date. 的本地化字符串。
        /// </summary>
        internal static string FlagCustomDescription {
            get {
                return ResourceManager.GetString("FlagCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task for next week. 的本地化字符串。
        /// </summary>
        internal static string FlagNextWeekDescription {
            get {
                return ResourceManager.GetString("FlagNextWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task with no due date. 的本地化字符串。
        /// </summary>
        internal static string FlagNoDatekDescription {
            get {
                return ResourceManager.GetString("FlagNoDatekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task to due at the end of the work week. 的本地化字符串。
        /// </summary>
        internal static string FlagThisWeekDescription {
            get {
                return ResourceManager.GetString("FlagThisWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task with a due date of today. 的本地化字符串。
        /// </summary>
        internal static string FlagTodayDescription {
            get {
                return ResourceManager.GetString("FlagTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag this item as a task with a due date of tomorrow. 的本地化字符串。
        /// </summary>
        internal static string FlagTomorrowDescription {
            get {
                return ResourceManager.GetString("FlagTomorrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip the layout of controls around a vertical axis. 的本地化字符串。
        /// </summary>
        internal static string FlipLayoutDescription {
            get {
                return ResourceManager.GetString("FlipLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward this item to someone else. 的本地化字符串。
        /// </summary>
        internal static string ForwardDescription {
            get {
                return ResourceManager.GetString("ForwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///=================End of original message text=============== 的本地化字符串。
        /// </summary>
        internal static string ForwardTextEnd {
            get {
                return ResourceManager.GetString("ForwardTextEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a forwarded message:
        ///
        ///=================Original message text===============
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string ForwardTextStart {
            get {
                return ResourceManager.GetString("ForwardTextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frameworks 的本地化字符串。
        /// </summary>
        internal static string Frameworks {
            get {
                return ResourceManager.GetString("Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To/From 的本地化字符串。
        /// </summary>
        internal static string FromDeleted {
            get {
                return ResourceManager.GetString("FromDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        internal static string FromInbox {
            get {
                return ResourceManager.GetString("FromInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        internal static string FromOutbox {
            get {
                return ResourceManager.GetString("FromOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GridContacts {
            get {
                object obj = ResourceManager.GetObject("GridContacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GridTasks {
            get {
                object obj = ResourceManager.GetObject("GridTasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap High16x16 {
            get {
                object obj = ResourceManager.GetObject("High16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 High priority 的本地化字符串。
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML files (*.html)|*.html 的本地化字符串。
        /// </summary>
        internal static string HTMLFilter {
            get {
                return ResourceManager.GetString("HTMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IDE Tools 的本地化字符串。
        /// </summary>
        internal static string IDETools {
            get {
                return ResourceManager.GetString("IDETools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMP files (*.bmp)|*.bmp|Gif files (*.gif)|*.gif|Jpeg files (*.jpeg)|*.jpeg|PNG files (*.png)|*.png|Tiff files (*.tiff)|*.tiff|EMF files (*.emf)|.emf|WMF files (*.wmf)|*.wmf 的本地化字符串。
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Important_16x16 {
            get {
                object obj = ResourceManager.GetObject("Important_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Inbox 的本地化字符串。
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ITEMS: {0} 的本地化字符串。
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is earlier this month 的本地化字符串。
        /// </summary>
        internal static string IsEarlierThisMonth {
            get {
                return ResourceManager.GetString("IsEarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is earlier this week 的本地化字符串。
        /// </summary>
        internal static string IsEarlierThisWeek {
            get {
                return ResourceManager.GetString("IsEarlierThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is earlier this year 的本地化字符串。
        /// </summary>
        internal static string IsEarlierThisYear {
            get {
                return ResourceManager.GetString("IsEarlierThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is last week 的本地化字符串。
        /// </summary>
        internal static string IsLastWeek {
            get {
                return ResourceManager.GetString("IsLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Today 的本地化字符串。
        /// </summary>
        internal static string IsToday {
            get {
                return ResourceManager.GetString("IsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is yesterday 的本地化字符串。
        /// </summary>
        internal static string IsYesterday {
            get {
                return ResourceManager.GetString("IsYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape Orientation 的本地化字符串。
        /// </summary>
        internal static string LandscapeOrientation {
            get {
                return ResourceManager.GetString("LandscapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LayoutFlip_16x16 {
            get {
                object obj = ResourceManager.GetObject("LayoutFlip_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LayoutFlip_32x32 {
            get {
                object obj = ResourceManager.GetObject("LayoutFlip_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap List_32x32 {
            get {
                object obj = ResourceManager.GetObject("List_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ListByDate_32x32 {
            get {
                object obj = ResourceManager.GetObject("ListByDate_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Low16x16 {
            get {
                object obj = ResourceManager.GetObject("Low16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Low priority 的本地化字符串。
        /// </summary>
        internal static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail 的本地化字符串。
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail 的本地化字符串。
        /// </summary>
        internal static string MailName {
            get {
                return ResourceManager.GetString("MailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moderate 的本地化字符串。
        /// </summary>
        internal static string MarginsModerate {
            get {
                return ResourceManager.GetString("MarginsModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top:	25 mm	Bottom:	25 mm
        ///Left:	19 mm	Right:	19 mm 的本地化字符串。
        /// </summary>
        internal static string MarginsModerateDescription {
            get {
                return ResourceManager.GetString("MarginsModerateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Narrow 的本地化字符串。
        /// </summary>
        internal static string MarginsNarrow {
            get {
                return ResourceManager.GetString("MarginsNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top:	12 mm	Bottom:	12 mm
        ///Left:	12 mm	Right:	12 mm 的本地化字符串。
        /// </summary>
        internal static string MarginsNarrowDescription {
            get {
                return ResourceManager.GetString("MarginsNarrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string MarginsNormal {
            get {
                return ResourceManager.GetString("MarginsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top:	25 mm	Bottom:	25 mm
        ///Left:	25 mm	Right:	25 mm 的本地化字符串。
        /// </summary>
        internal static string MarginsNormalDescription {
            get {
                return ResourceManager.GetString("MarginsNormalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wide 的本地化字符串。
        /// </summary>
        internal static string MarginsWide {
            get {
                return ResourceManager.GetString("MarginsWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top:	25 mm	Bottom:	25 mm
        ///Left:	50 mm	Right:	50 mm 的本地化字符串。
        /// </summary>
        internal static string MarginsWideDescription {
            get {
                return ResourceManager.GetString("MarginsWideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium priority 的本地化字符串。
        /// </summary>
        internal static string MediumPriority {
            get {
                return ResourceManager.GetString("MediumPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MemoStyle {
            get {
                object obj = ResourceManager.GetObject("MemoStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Memo Style 的本地化字符串。
        /// </summary>
        internal static string MemoStyleString {
            get {
                return ResourceManager.GetString("MemoStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MHT files (*.mht)|*.mht 的本地化字符串。
        /// </summary>
        internal static string MHTFilter {
            get {
                return ResourceManager.GetString("MHTFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Miss {
            get {
                object obj = ResourceManager.GetObject("Miss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mr {
            get {
                object obj = ResourceManager.GetObject("Mr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mrs {
            get {
                object obj = ResourceManager.GetObject("Mrs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ms {
            get {
                object obj = ResourceManager.GetObject("Ms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MultiplePagesLarge {
            get {
                object obj = ResourceManager.GetObject("MultiplePagesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NavigationBar_16x16 {
            get {
                object obj = ResourceManager.GetObject("NavigationBar_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NavigationBar_32x32 {
            get {
                object obj = ResourceManager.GetObject("NavigationBar_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Switch between modules. 的本地化字符串。
        /// </summary>
        internal static string NavigationDescription {
            get {
                return ResourceManager.GetString("NavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NewContact_16x16 {
            get {
                object obj = ResourceManager.GetObject("NewContact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NewContact_32x32 {
            get {
                object obj = ResourceManager.GetObject("NewContact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new contact. 的本地化字符串。
        /// </summary>
        internal static string NewContactDescription {
            get {
                return ResourceManager.GetString("NewContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new feed. 的本地化字符串。
        /// </summary>
        internal static string NewFeedDescription {
            get {
                return ResourceManager.GetString("NewFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string NewFirstName {
            get {
                return ResourceManager.GetString("NewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new mail. 的本地化字符串。
        /// </summary>
        internal static string NewItemDescription {
            get {
                return ResourceManager.GetString("NewItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string NewLastName {
            get {
                return ResourceManager.GetString("NewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NewTask_16x16 {
            get {
                object obj = ResourceManager.GetObject("NewTask_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NewTask_32x32 {
            get {
                object obj = ResourceManager.GetObject("NewTask_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new task. 的本地化字符串。
        /// </summary>
        internal static string NewTaskDescription {
            get {
                return ResourceManager.GetString("NewTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New task 的本地化字符串。
        /// </summary>
        internal static string NewTaskName {
            get {
                return ResourceManager.GetString("NewTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Week 的本地化字符串。
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NextWeek_Flag {
            get {
                object obj = ResourceManager.GetObject("NextWeek_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 No Date 的本地化字符串。
        /// </summary>
        internal static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NoDate_Flag {
            get {
                object obj = ResourceManager.GetObject("NoDate_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print One Sided 的本地化字符串。
        /// </summary>
        internal static string OneSide {
            get {
                return ResourceManager.GetString("OneSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only print on one side of the page 的本地化字符串。
        /// </summary>
        internal static string OneSideDescription {
            get {
                return ResourceManager.GetString("OneSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Online_Help {
            get {
                object obj = ResourceManager.GetObject("Online_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to open this file? 的本地化字符串。
        /// </summary>
        internal static string OpentFileQuestion {
            get {
                return ResourceManager.GetString("OpentFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Overdue_32x32 {
            get {
                object obj = ResourceManager.GetObject("Overdue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Owner {
            get {
                object obj = ResourceManager.GetObject("Owner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Mr.Brooks 的本地化字符串。
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} of  的本地化字符串。
        /// </summary>
        internal static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsModerate {
            get {
                object obj = ResourceManager.GetObject("PageMarginsModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsNarrow {
            get {
                object obj = ResourceManager.GetObject("PageMarginsNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsNormal {
            get {
                object obj = ResourceManager.GetObject("PageMarginsNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsWide {
            get {
                object obj = ResourceManager.GetObject("PageMarginsWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageOrientationLandscape {
            get {
                object obj = ResourceManager.GetObject("PageOrientationLandscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PageOrientationPortrait {
            get {
                object obj = ResourceManager.GetObject("PageOrientationPortrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pagesetup_32x32 {
            get {
                object obj = ResourceManager.GetObject("pagesetup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A3 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A4 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A5 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A6 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Executive {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Executive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Legal {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Letter {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Tabloid {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Tabloid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 A3 的本地化字符串。
        /// </summary>
        internal static string PaperKindA3 {
            get {
                return ResourceManager.GetString("PaperKindA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 296 mm x 420 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindA3Description {
            get {
                return ResourceManager.GetString("PaperKindA3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A4 的本地化字符串。
        /// </summary>
        internal static string PaperKindA4 {
            get {
                return ResourceManager.GetString("PaperKindA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 210 mm x 296 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindA4Description {
            get {
                return ResourceManager.GetString("PaperKindA4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A5 的本地化字符串。
        /// </summary>
        internal static string PaperKindA5 {
            get {
                return ResourceManager.GetString("PaperKindA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 148 mm x 210 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindA5Description {
            get {
                return ResourceManager.GetString("PaperKindA5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A6 的本地化字符串。
        /// </summary>
        internal static string PaperKindA6 {
            get {
                return ResourceManager.GetString("PaperKindA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 105 mm x 148 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindA6Description {
            get {
                return ResourceManager.GetString("PaperKindA6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executive 的本地化字符串。
        /// </summary>
        internal static string PaperKindExecutive {
            get {
                return ResourceManager.GetString("PaperKindExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 184 mm x 266 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindExecutiveDescription {
            get {
                return ResourceManager.GetString("PaperKindExecutiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal 的本地化字符串。
        /// </summary>
        internal static string PaperKindLegal {
            get {
                return ResourceManager.GetString("PaperKindLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 215 mm x 355 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindLegalDescription {
            get {
                return ResourceManager.GetString("PaperKindLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Letter 的本地化字符串。
        /// </summary>
        internal static string PaperKindLetter {
            get {
                return ResourceManager.GetString("PaperKindLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 215 mm x 279 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindLetterDescription {
            get {
                return ResourceManager.GetString("PaperKindLetterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabloid 的本地化字符串。
        /// </summary>
        internal static string PaperKindTabloid {
            get {
                return ResourceManager.GetString("PaperKindTabloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 279 mm x 431 mm 的本地化字符串。
        /// </summary>
        internal static string PaperKindTabloidDescription {
            get {
                return ResourceManager.GetString("PaperKindTabloidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF files (*.pdf)|*.pdf 的本地化字符串。
        /// </summary>
        internal static string PDFFilter {
            get {
                return ResourceManager.GetString("PDFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PDFViewer {
            get {
                object obj = ResourceManager.GetObject("PDFViewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Personal 的本地化字符串。
        /// </summary>
        internal static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br&gt;Phone: &lt;b&gt;{0}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string PhoneHtml {
            get {
                return ResourceManager.GetString("PhoneHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Image 的本地化字符串。
        /// </summary>
        internal static string Picture100Zoom {
            get {
                return ResourceManager.GetString("Picture100Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Pivot {
            get {
                object obj = ResourceManager.GetObject("Pivot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait Orientation 的本地化字符串。
        /// </summary>
        internal static string PortraitOrientation {
            get {
                return ResourceManager.GetString("PortraitOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PrintDirectLarge {
            get {
                object obj = ResourceManager.GetObject("PrintDirectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Prioritized_32x32 {
            get {
                object obj = ResourceManager.GetObject("Prioritized_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Priority_16x16 {
            get {
                object obj = ResourceManager.GetObject("Priority_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Set priority for this item. 的本地化字符串。
        /// </summary>
        internal static string PriorityDescription {
            get {
                return ResourceManager.GetString("PriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        internal static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        internal static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Professor {
            get {
                object obj = ResourceManager.GetObject("Professor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait 的本地化字符串。
        /// </summary>
        internal static string ProgressPanelCaption {
            get {
                return ResourceManager.GetString("ProgressPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading ... 的本地化字符串。
        /// </summary>
        internal static string ProgressPanelDescription {
            get {
                return ResourceManager.GetString("ProgressPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap reading {
            get {
                object obj = ResourceManager.GetObject("reading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_32x32 {
            get {
                object obj = ResourceManager.GetObject("Refresh_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Reload this feed from the server. 的本地化字符串。
        /// </summary>
        internal static string RefreshFeedDescription {
            get {
                return ResourceManager.GetString("RefreshFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap reminder {
            get {
                object obj = ResourceManager.GetObject("reminder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 REMINDERS: {0} 的本地化字符串。
        /// </summary>
        internal static string ReminderText {
            get {
                return ResourceManager.GetString("ReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply to the sender and all other recipients of this message. 的本地化字符串。
        /// </summary>
        internal static string ReplyAllDescription {
            get {
                return ResourceManager.GetString("ReplyAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply to the sender of this message. 的本地化字符串。
        /// </summary>
        internal static string ReplyDescription {
            get {
                return ResourceManager.GetString("ReplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dear, {0}
        ///
        ///{1}, you wrote:
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string ReplyText {
            get {
                return ResourceManager.GetString("ReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate the layout of controls. 的本地化字符串。
        /// </summary>
        internal static string RotateLayoutDescription {
            get {
                return ResourceManager.GetString("RotateLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RTF files (*.rtf)|*.rtf 的本地化字符串。
        /// </summary>
        internal static string RTFFilter {
            get {
                return ResourceManager.GetString("RTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This value cannot be empty 的本地化字符串。
        /// </summary>
        internal static string RuleIsNotBlankWarning {
            get {
                return ResourceManager.GetString("RuleIsNotBlankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This value must be unique and does not equal empty. 的本地化字符串。
        /// </summary>
        internal static string RuleUniqueNamesWarning {
            get {
                return ResourceManager.GetString("RuleUniqueNamesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x16 {
            get {
                object obj = ResourceManager.GetObject("Save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_32x32 {
            get {
                object obj = ResourceManager.GetObject("Save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SaveAll_32x32 {
            get {
                object obj = ResourceManager.GetObject("SaveAll_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes? 的本地化字符串。
        /// </summary>
        internal static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Scheduler {
            get {
                object obj = ResourceManager.GetObject("Scheduler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the applied filter. 的本地化字符串。
        /// </summary>
        internal static string SearchClearDescription {
            get {
                return ResourceManager.GetString("SearchClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close the Search tab. 的本地化字符串。
        /// </summary>
        internal static string SearchCloseDescription {
            get {
                return ResourceManager.GetString("SearchCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select columns against which a search is performed. 的本地化字符串。
        /// </summary>
        internal static string SearchColumnsDescription {
            get {
                return ResourceManager.GetString("SearchColumnsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display e-mail messages that have attachments. 的本地化字符串。
        /// </summary>
        internal static string SearchHasAttachmentDescription {
            get {
                return ResourceManager.GetString("SearchHasAttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display prioritized e-mail messages. 的本地化字符串。
        /// </summary>
        internal static string SearchImportantDescription {
            get {
                return ResourceManager.GetString("SearchImportantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter e-mail messages by date. 的本地化字符串。
        /// </summary>
        internal static string SearchReceivedDescription {
            get {
                return ResourceManager.GetString("SearchReceivedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to the default filter column list. 的本地化字符串。
        /// </summary>
        internal static string SearchResetDescription {
            get {
                return ResourceManager.GetString("SearchResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search {0} (Ctrl + E) 的本地化字符串。
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display unread e-mail messages. 的本地化字符串。
        /// </summary>
        internal static string SearchUnreadDescription {
            get {
                return ResourceManager.GetString("SearchUnreadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent Items 的本地化字符串。
        /// </summary>
        internal static string SentItems {
            get {
                return ResourceManager.GetString("SentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display message previews 的本地化字符串。
        /// </summary>
        internal static string ShowPreviewDescription {
            get {
                return ResourceManager.GetString("ShowPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SortAsc_32x32 {
            get {
                object obj = ResourceManager.GetObject("SortAsc_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Spreadsheet {
            get {
                object obj = ResourceManager.GetObject("Spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Starting 的本地化字符串。
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap TableStyle {
            get {
                object obj = ResourceManager.GetObject("TableStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Table Style 的本地化字符串。
        /// </summary>
        internal static string TableStyleString {
            get {
                return ResourceManager.GetString("TableStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 House Chores 的本地化字符串。
        /// </summary>
        internal static string TaskCategoryHouseChores {
            get {
                return ResourceManager.GetString("TaskCategoryHouseChores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work 的本地化字符串。
        /// </summary>
        internal static string TaskCategoryOffice {
            get {
                return ResourceManager.GetString("TaskCategoryOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shopping 的本地化字符串。
        /// </summary>
        internal static string TaskCategoryShopping {
            get {
                return ResourceManager.GetString("TaskCategoryShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List completed tasks and group them by date. 的本地化字符串。
        /// </summary>
        internal static string TaskCompletedDescription {
            get {
                return ResourceManager.GetString("TaskCompletedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List deferred tasks. 的本地化字符串。
        /// </summary>
        internal static string TaskDeferredDescription {
            get {
                return ResourceManager.GetString("TaskDeferredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List all tasks and group them by date. 的本地化字符串。
        /// </summary>
        internal static string TaskListDescription {
            get {
                return ResourceManager.GetString("TaskListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List overdue tasks. 的本地化字符串。
        /// </summary>
        internal static string TaskOverdueDescription {
            get {
                return ResourceManager.GetString("TaskOverdueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group tasks by priority. 的本地化字符串。
        /// </summary>
        internal static string TaskPrioritizedDescription {
            get {
                return ResourceManager.GetString("TaskPrioritizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List all tasks. 的本地化字符串。
        /// </summary>
        internal static string TaskSimpleListDescription {
            get {
                return ResourceManager.GetString("TaskSimpleListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        internal static string TasksName {
            get {
                return ResourceManager.GetString("TasksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string TaskStatusCompleted {
            get {
                return ResourceManager.GetString("TaskStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deferred 的本地化字符串。
        /// </summary>
        internal static string TaskStatusDeferred {
            get {
                return ResourceManager.GetString("TaskStatusDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Progress 的本地化字符串。
        /// </summary>
        internal static string TaskStatusInProgress {
            get {
                return ResourceManager.GetString("TaskStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Started 的本地化字符串。
        /// </summary>
        internal static string TaskStatusNotStarted {
            get {
                return ResourceManager.GetString("TaskStatusNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting On Someone Else 的本地化字符串。
        /// </summary>
        internal static string TaskStatusWaitingOnSomeoneElse {
            get {
                return ResourceManager.GetString("TaskStatusWaitingOnSomeoneElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List Today&apos;s tasks. 的本地化字符串。
        /// </summary>
        internal static string TaskTodayDescription {
            get {
                return ResourceManager.GetString("TaskTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List non-completed tasks and group them by date. 的本地化字符串。
        /// </summary>
        internal static string TaskToDoListDescription {
            get {
                return ResourceManager.GetString("TaskToDoListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyFeed 的本地化字符串。
        /// </summary>
        internal static string TempFeedName {
            get {
                return ResourceManager.GetString("TempFeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyGroup 的本地化字符串。
        /// </summary>
        internal static string TempGroupName {
            get {
                return ResourceManager.GetString("TempGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap textbox_32x32 {
            get {
                object obj = ResourceManager.GetObject("textbox_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Text files (*.txt)|*.txt 的本地化字符串。
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Week 的本地化字符串。
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ThisWeek_Flag {
            get {
                object obj = ResourceManager.GetObject("ThisWeek_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Today_16x16 {
            get {
                object obj = ResourceManager.GetObject("Today_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Today_32x32 {
            get {
                object obj = ResourceManager.GetObject("Today_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Today_Flag {
            get {
                object obj = ResourceManager.GetObject("Today_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ToDoList_32x32 {
            get {
                object obj = ResourceManager.GetObject("ToDoList_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Tomorrow 的本地化字符串。
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Tomorrow_Flag {
            get {
                object obj = ResourceManager.GetObject("Tomorrow_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Manually Print on Both Sides 的本地化字符串。
        /// </summary>
        internal static string TwoSide {
            get {
                return ResourceManager.GetString("TwoSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload paper when prompted to print the second side 的本地化字符串。
        /// </summary>
        internal static string TwoSideDescription {
            get {
                return ResourceManager.GetString("TwoSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncollated 的本地化字符串。
        /// </summary>
        internal static string Uncollated {
            get {
                return ResourceManager.GetString("Uncollated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1,1,1  2,2,2  3,3,3 的本地化字符串。
        /// </summary>
        internal static string UncollatedDescription {
            get {
                return ResourceManager.GetString("UncollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Universal {
            get {
                object obj = ResourceManager.GetObject("Universal", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Unknown_user {
            get {
                object obj = ResourceManager.GetObject("Unknown_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 If this item is marked as unread mark it as read.
        ///If this item is marked as read mark it as though you haven&apos;t read it yet. 的本地化字符串。
        /// </summary>
        internal static string UnreadReadDescription {
            get {
                return ResourceManager.GetString("UnreadReadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WeatherMap {
            get {
                object obj = ResourceManager.GetObject("WeatherMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Win {
            get {
                object obj = ResourceManager.GetObject("Win", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 WinForms 的本地化字符串。
        /// </summary>
        internal static string WinForms {
            get {
                return ResourceManager.GetString("WinForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WordProcessing {
            get {
                object obj = ResourceManager.GetObject("WordProcessing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Work 的本地化字符串。
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WYSIWYGReports {
            get {
                object obj = ResourceManager.GetObject("WYSIWYGReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 XLS files (*.xls)|*.xls 的本地化字符串。
        /// </summary>
        internal static string XLSFilter {
            get {
                return ResourceManager.GetString("XLSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XLSX files (*.xls)|*.xls 的本地化字符串。
        /// </summary>
        internal static string XLSXFilter {
            get {
                return ResourceManager.GetString("XLSXFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoom100_32x32 {
            get {
                object obj = ResourceManager.GetObject("zoom100_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
